version: 0.2

env:
  variables:
    CI: true
    FORCE_COLOR: 0
    DOCS_SITE_URL: https://cybonyx-docs-site.com

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - npm install -g yarn "serverless@^3.0.0"
  pre_build:
    commands:
      - yarn install
  build:
    on-failure: ABORT
    commands:
      - yarn run lint
      - yarn run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync ./build/ s3://dev-docs-site-eu-west-2/ --delete 

      - serverless deploy --region "$AWS_DEFAULT_REGION" --stage "$STAGE"
      - echo "Build completed on $(date)"
