version: 0.2

env:
  variables:
    CI: true
    FORCE_COLOR: 0
    HOSTING_BUCKET: cybonyx-dev-docs-site-hosting-eu-west-2
    AWS_DEFAULT_REGION: eu-west-2

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - npm install -g yarn "serverless@^3.0.0"
  pre_build:
    commands:
      - yarn install
  build:
    on-failure: ABORT
    commands:
      - yarn run lint
      - yarn run build
  post_build:
    commands:
      - echo "Deploying static site to S3..."
      - aws s3 sync ./build/ s3://$HOSTING_BUCKET/ --region "$AWS_DEFAULT_REGION"

      - echo "Deploying API with Serverless..."
      - serverless deploy --region "$AWS_DEFAULT_REGION" --stage "$STAGE"

      - echo "Build completed on $(date)"

