service: docs-site

provider:
  name: aws
  stage: dev
  region: eu-west-2
  environment:
    HOSTING_BUCKET_NAME: ${self:custom.hostingBucketName}
    DOCS_BUCKET_NAME: ${self:custom.docsBucketName}
  stackTags:
    Name: ${self:service}
    Description: A simple static site for documentation
    Owner: ${self:custom.tags.owner}
    OwnerFunction: ${self:custom.tags.ownerFunction}

plugins:
  - serverless-offline

custom:
  hostingBucketName: ${self:provider.stage}-docs-site-hosting-${self:provider.region}
  docsBucketName: ${self:provider.stage}-docs-site-docs-${self:provider.region}
  tags:
    owner: ${env:OWNER,'N/A'}
    ownerFunction: ${env:OWNER_FUNCTION,'N/A'}
  serverless-offline:
    httpPort: 3001
    
resources:
  Resources:
    HostingS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.hostingBucketName}
      DeletionPolicy: Retain  # Prevent CloudFormation from deleting the bucket

    DocsS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.docsBucketName}
      DeletionPolicy: Retain  # Prevent CloudFormation from deleting the bucket

    HostingS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref HostingS3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:GetObject"
              Resource: !Sub "arn:aws:s3:::${self:custom.hostingBucketName}/*"
              Principal: "*"

    DocsS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref DocsS3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:GetObject"
              Resource: !Sub "arn:aws:s3:::${self:custom.docsBucketName}/*"
              Principal: "*"

functions:
  deleteMarkdown:
    handler: src/handler.deleteMarkdown
    events:
      - http:
          path: delete
          method: delete
          cors: true

  getContent:
    handler: src/handler.getContent
    events:
      - http:
          path: pages/{filePath*} # Single function handles everything
          method: get
          cors: true

  uploadMarkdown:
    handler: src/handler.uploadMarkdown
    events:
      - http:
          path: upload
          method: post
          cors: true

  saveContent:
    handler: src/handler.saveContent
    events:
      - http:
          path: pages/{filePath*}
          method: put
          cors: true