service: docs-site

provider:
  name: aws
  stage: dev
  region: eu-west-2
  stackTags:
    Name: ${self:service}
    Description: A simple static site for documentation
    Owner: ${self:custom.tags.owner}
    OwnerFunction: ${self:custom.tags.ownerFunction}
    Customer: ${self:custom.tags.customer}

custom:
  bucketName: ${self:provider.stage}-docs-site-${self:provider.region}
  tags:
    owner: ${env:OWNER,'N/A'}
    ownerFunction: ${env:OWNER_FUNCTION,'N/A'}
    customer: ${env:CUSTOMER,'i1'}
plugins:
  - serverless-plugin-safe-s3-upload

resources:
  Resources:
    DocsSiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
