service: docs-site

provider:
  name: aws
  stage: dev
  region: eu-west-2
  logRetentionInDays: 14  # Keeps logs for 14 days, adjust as needed
  runtime: nodejs22.x
  environment:
    HOSTING_BUCKET_NAME: ${self:custom.hostingBucketName}
    DOCS_BUCKET_NAME: ${self:custom.docsBucketName}
  stackTags:
    Name: ${self:service}
    Description: A simple static site for documentation
    Owner: ${self:custom.tags.owner}
    OwnerFunction: ${self:custom.tags.ownerFunction}

plugins:
  - serverless-offline

resources:
  Resources:
    HostingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.hostingBucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
    DocsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.docsBucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
    HostingBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref HostingBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: "arn:aws:s3:::${self:custom.hostingBucketName}/*"

    DocsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref DocsBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: "arn:aws:s3:::${self:custom.docsBucketName}/*"

custom:
  hostingBucketName: cybonyx-${self:provider.stage}-docs-site-hosting-${self:provider.region}
  docsBucketName: cybonyx-${self:provider.stage}-docs-site-docs-${self:provider.region}
  tags:
    owner: ${env:OWNER,'N/A'}
    ownerFunction: ${env:OWNER_FUNCTION,'N/A'}
  serverless-offline:
    httpPort: 3001
    
functions:
  deleteMarkdown:
    handler: src/handler.deleteMarkdown
    events:
      - http:
          path: delete
          method: delete
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getContent:
    handler: src/handler.getContent
    events:
      - http:
          path: pages/{filePath+} # Single function handles everything
          method: get
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  uploadMarkdown:
    handler: src/handler.uploadMarkdown
    events:
      - http:
          path: upload
          method: post
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  saveContent:
    handler: src/handler.saveContent
    events:
      - http:
          path: pages/{filePath+}
          method: put
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
